### ISSUE TITLE
Example crashing with (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

### ISSUE THREAD

**Issue by MTRNord** [apoloval/fsuipc-rs#2]
Hi I tried to use this with XP11 running and the example. I confirmed that the fsuipc/xpuipc plugin in XP11 is running.

However trying to run the example I get this error on recent rust with windows 11. Any ideas what might be going on?

**Comment by MTRNord** [comment]
Hm interesting enough the fsuipc C sdk v2 does say that the ipc request would contain bad data. So maybe this is an issue with xp11?

![image](https://user-images.githubusercontent.com/1374914/159070208-8ce303c1-dbfb-4348-87d2-5bea380315a8.png)

**Comment by MTRNord** [comment]
Nvm issue is that i used 64bits instead of 32bits

**Comment by watsom27** [comment]
@MTRNord Hello, How did you get this working? What do you mean by `used 64bits instead of 32bits`?
